name: CI/CD Bucket

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install npm dependencies
        run: yarn

      - name: Run build task
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: make artiface
          path: build

      - name: Authenticate on GCS
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      - name: Depoly to Bucket
        run: gsutil -m cp -r build/* gs://live.seongland.com
